# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# variables
export EDITOR='vim'
export VISUAL='vim'
export PAGER='vimpager'
export TERM='rxvt-unicode'

# aliases
alias sudo='sudo '
alias pacman='pacnanny'
alias syu='sudo pacnanny -Syu'
alias syua='pacaur -Syua'
echol='echo ~/Downloads/$(ls -c ~/Downloads 2>/dev/null | head -1)'

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-ocean.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

function pp {
    # remember output, prevent different clipboard contents
    # after choosing to execute
    script=$(xclip -o)
    cat -A <<< $script
    printf "\nExecute? (y/n): "
    read execute
    # only execute when 'y' was answered
    # all other input is ignored
    if [[ "$execute" == "y" ]]; then
        eval "$script"
    fi
}
# cf - fuzzy cd from anywhere
# ex: cf word1 word2 ... (even part of a file name)
# zsh autoload function
cf() {
  local file

  file="$(locate -Ai -0 $@ | grep -z -vE '~$' | fzf --read0 -0 -1)"

  if [[ -n $file ]]
  then
     if [[ -d $file ]]
     then
        cd -- $file
     else
        cd -- ${file:h}
     fi
  fi
}

eval "$(fasd --init auto)"
